name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.0.0-dev.4
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  meta: ^1.3.0
  rxdart: ^0.26.0
  uuid: ^3.0.1
  webview_flutter: ^2.0.2


dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  test: ^1.6.3

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
